### ISSUE TITLE
Fidelity OFX alternatives

### ISSUE THREAD

**Issue by thehilll** [redstreet/beancount_reds_importers#170]
Fidelity seems to have pulled the plug on OFX downloads.  They worked as recently as this weekend, but now I'm getting access denied which seems to be an issue for others as well:

https://github.com/csingley/ofxtools/issues/200

The Reddit link in that issue discusses an impending move to allow only Quicken EWC+ and CSV downloads via a manual web interaction.

I was looking at the content and discussion history of your Fidelity CSV importers.  The columns seem to have changed, but I could take a look at a PR for updating those.  I was wondering if you had any other ideas as to alternatives.  This is a pretty painful issue for me, so I'm open to options.  It does not seem possible for tools other than Quicken to use EWC+, and from what I can tell services like Plaid and MX (both of which seem to be accessible via a third party wrapper we could use) don't support Fidelity either.

Thanks for any suggestions you might have.

**Comment by redstreet** [comment]
Thanks for filing! I'm getting the same thing today, although Fidelity has gone out every now and then and then come back just fine. The problem though, is Fidelity doesn't allow downloads of `ofx` via their website (and only allow it via Direct Connect), which is annoying.

IMO, a `.csv` importer is always a great idea given all institutions support these well through their web interface. I'd suggest starting fresh from scratch. They're easy to write: see [schwab csv importer](https://github.com/redstreet/beancount_reds_importers/blob/1029d63e5778f653d2fe3d58203e49c896bbd40f/beancount_reds_importers/importers/schwab/schwab_csv_brokerage.py).

I'd happy to review a PR for it as long as there are unit tests, which I'd recommend using AI to generate. In fact, you could probably dump the Schwab csv importer, a Fidelity csv sample, and ask AI to write the importer for you. Hope that helps!

**Comment by thehilll** [comment]
Thanks, and for example data...this fund info
```
fund_data = [
    ('GEV', '36828A101', 'GE VERNOVA INC COM'),
    ('VGK', '922042874', 'VANGUARD INTL EQUITY INDEX FDS FTSE EUROPE ETF'),
]
```

with the attached csv should show it.

[example.csv](https://github.com/user-attachments/files/23917960/example.csv)

**Comment by thehilll** [comment]
Sorry to keep adding to this before you've had a chance to look, but after thinking about it I think a better solution is to do the substring matching only when not using `funds_by_ticker`.  The substrings when using cusip is a real issue (I've run into it when I was still able to use ofx), so I don't think it makes sense to not use it at all.  At the same time, I think this block is bound to cause issues when using ticker symbols...there are just too many short ticker symbols of commonly held stocks.

I've modified the two locations that were using the substring match to only do so when matching on cusip and pushed it here:

https://github.com/thehilll/beancount_reds_importers/blob/d04acf0f72ecad2135c35912b80610fa2cc2098f/beancount_reds_importers/libtransactionbuilder/investments.py#L152-L183

**Comment by redstreet** [comment]
Hello @thehilll, thank you for all the progress on this! It looks like I'm not going to be able to look into it this weekend, so it'll have to be next week some time. But I personally depend on a working Fidelity importer, and therefore will definitely get this resolved.

I'll try to send some comments meanwhile.

**Comment by thehilll** [comment]
So I think I'm ready to do a PR, but now I've run into my limited experience w/git and PRs.

Because I wanted to test this on my import process I created my branch off of the `0.10.0` tag that uses Beancount v2.  Now I come to find out that I cannot do a pull request against a tag, only a branch (which makes sense now that I have read about it).

@redstreet how should I proceed?  I could migrate all of my changes to a new fork if you were to crate a branch based of of `0.10.0`, but I really don't know what the best solution is here.

**Comment by redstreet** [comment]
Sure:

1. This is all I had to do to get it to work with v3:
```
from beangulp import cache
def deep_identify(self, file):
    return re.search(self.header_identifier, cache.get_file(file).head(), flags=re.MULTILINE)
```

2. I can't release a 0.10.1 as I release off `main`, and it's too late to do that. However, I just created a new branch `beancount_v2` based off of 0.10.0 [here](https://github.com/redstreet/beancount_reds_importers/tree/beancount_v2). You can target a v2 PR against it if you'd like

**Comment by thehilll** [comment]
Looks like my PR and your new branch were close to simultaneous.  Let me know if you'd like me to use the new branch vs. the PR I just did.

On 2 above I will do as you suggest.

**Comment by JustinDSN** [comment]
Would you mind sharing the web navigation flow you follow on Fidelity's site to download the [example.csv](https://github.com/user-attachments/files/23917960/example.csv)? I can't seem to get the expanded version downloaded for my Fidelity NetBenifits accounts. 

The CSV's I download only contain a few fields that don't seem sufficient for importers.

The flow I follow is: 
* Click "Retirement Account Name"  
* Click "Transaction History" on the Summary Page 
* Click "Transaction History" 
* Click "Download Transaction History" 
* Select time period and file format of CSV and click Download. 
* The files I download only contain a few fields: [retirement_example.csv](https://github.com/user-attachments/files/24333737/retirement_example.csv)

**Comment by scanta2** [comment]
> I click on "All accounts" at the top of the account selector column then "Activity & Orders" in the main panel. This creates a download with a much broader set of columns (and consistent across the accounts). The work we've been doing here works on these CSVs (I tested with some of my 401(k) account transactions).

I am also not getting all of the columns. I am missing columns related to Exchanges.

**Comment by scanta2** [comment]
@sushain97 Can you please share your importer config? I still have trouble with the `($)` header substrings, but I am thinking it might be something that I can set in the importer config? I haven't debugged yet.

**Comment by thehilll** [comment]
> > edit: Things... worked until they crashed with two edits:
> > ```
> > 1. Removing the ` ($)` from the header row.
> > 
> > 2. Setting `self.column_labels_line = "Run Date,Account,Account Number,Action,Symbol,Description,Type,Price,Quantity,Commission,Fees,Accrued Interest,Amount,Settlement Date"`
> > ```

Unfortunately I think it is clear that there is no hard-coded header row that will work.  Fidelity appears to dynamically generate this header row based on your specific accounts and there is no way to change this.

I think some of this can be addressed by making the `column_labels_line` and potentially `header_identifier` something that can be overridden in the config.

Incredibly they appear to have different labels for the same column (e.g. `Amount` vs. `Amount ($)`).  This is a more complex as this field is used to create the `total` field by referring to its original name.

> > Then, we failed at this line with `ERROR: unknown entry type: CO CONTR`:
> > ```
> > 12/22/2025,"Health Savings `Account","REDACTED","CO` CONTR CURRENT YR EMPLOYER CUR YR (Cash)",,"No Description",Cash,,0.000,,,,100,
> > ```

This is easier to fix via `transaction_type_map`, but does the `Action` field really contain that backtick?

**Comment by thehilll** [comment]
I've added the ability to override the `column_labels_line` and `header_identifier` settings in the config file, and I have tried to remove cases of ` ($)` from any column label (but this is _after_ the import, so that should remain in the two identifier variables). 

For example, you could set
```
"column_labels_line": "Run Date,Account,Account Number,Action,Symbol,Description,Type,Exchange Quantity,Exchange Currency,Currency,Price,Quantity,Exchange Rate,Commission,Fees,Accrued Interest,Amount ($),Settlement Date"
```
in your config.  The file will be read properly (whereas before the $ would mean the header line wasn't recognized), and the ` ($)` will be stripped out before the `Amount` field is used.

**Comment by thehilll** [comment]
I've also added the ability to override or extend `transaction_type_map` via a dict in the config.  Note 1, the keys should be upper case (regardless of what is in your csv...we have seen both), and you should match on the first two words of the action field.  There are cases where this has to be the first single word (e.g. when the second word will be a symbol), but that requires more involved changes.

**Comment by scanta2** [comment]
> > I haven't really reviewed the outputs but here are the changes required so that my CSVs don't result in a crash: [thehilll/beancount_reds_importers@fidelity_all_account_csv...sushain97:beancount_reds_importers:patch-1](https://github.com/thehilll/beancount_reds_importers/compare/fidelity_all_account_csv...sushain97:beancount_reds_importers:patch-1).
> > Edit: The branch above now contains all the tweaks necessary for my CSVs to convert correctly. I have some other tweaks locally as well to remove noisy fee entries but they're cosmetic.
> 
> [@sushain97](https://github.com/sushain97) , scanning through this there appears to be 3 (maybe 4) changes you've made:
> 
>     1. Changing the column labels
> 
>     2. Extending the `transaction_type_map`
> 
>     3. Adding `security_description_map` and handling situations where price is used for quantity in 401(k)
> 
> 
> I believe you should be able to do 1 and 2 in the new version I have pushed. I don't think we'll ever get to a static list of these as there is just too much variety (which just shows how customer-hostile this change from Fidelity is).
> 
> On 3 could you explain what you are seeing? I do not have 401(k) transactions that brought any of this up. My only concern would be breaking things for others. In any case this is probably a big enough structural change that it should probably be handled as a separate PR.
> 
> Also, everyone should know that my fork of this has not been fully integrated into Red's original. That is happening via individual PRs to a specific branch:
> 
> https://github.com/redstreet/beancount_reds_importers/tree/fidelity_all_csv
> 
> The hope is that eventually the more complex changes make it into the original, but that will take some time.

Thanks for these changes. I am going to test them soon. As far as the swapped Price/Quantity columns, could we just have a flag in the config to configure the behavior?

**Comment by thehilll** [comment]
> The two examples above are from different company 401K accounts but in both cases Fidelity doesn't seem to actually include the symbol, just a shortening of the security. And, they swap Price and Quantity…

Thanks a lot.  The `symbol_from_description` part seems safe enough because leaving that map empty basically disables it.  I'm a little worried about swapping quantity and price without some other restriction.  What do you think about adding a config item along the lines of `swap_quantity_and_price_accts` which would be a list of account numbers to which that logic would apply?

**Comment by scanta2** [comment]
In my case, `header_map` should also be overridden. `Action` is not a `memo` column, because `Type` for me is empty.
Here's an example, where the price/quantity fields are also swapped.

```
Run Date,Account,Account Number,Action,Symbol,Description,Type,Price ($),Quantity,Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
12/31/2025,"RETIREMENT PLN","12345","Contributions",,"FID EMERGING MKTS K",,0.692,,,,,34.52,,
```

**Comment by scanta2** [comment]
> > In my case, `header_map` should also be overridden. `Action` is not a `memo` column, because `Type` for me is empty. Here's an example, where the price/quantity fields are also swapped.
> > ```
> > Run Date,Account,Account Number,Action,Symbol,Description,Type,Price ($),Quantity,Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
> > 12/31/2025,"RETIREMENT PLN","12345","Contributions",,"FID EMERGING MKTS K",,0.692,,,,,34.52,,
> > ```
> 
> I don't understand? `Type` isn't used for anything. `Action` is used to determine the transaction type and is included in the transaction memo as well. I don't see why you can't just use a custom `header_identifier` and/or `column_labels_line`

I figured out the source of my confusion. I will post a comment in the relevant file.

**Comment by thehilll** [comment]
> A `"swap_quantity_and_price_values": True` key seems sufficient?

You are right.  Sorry, I was confusing this with my overall import process wrapper that uses it.  I should be able to get to this today or tomorrow.

**Comment by thehilll** [comment]
> In `fidelity_all_accounts_csv.py`, before returning `rdr`, the line to convert `type` to upper case should be `rdr = rdr.convert("type", "upper")`. Instead, you have `rdr.convert("type", "upper")` only.
> 
> With the original line, the mapping between original types and valid types could not be performed.

I see now.  I will fix this.

**Comment by sushain97** [comment]
@thehilll thanks! I've updated my version based on yours and here are the remaining changes: https://github.com/thehilll/beancount_reds_importers/commit/a9c43d911a16f8ca12fe2041e45b6f1ebf3ecb78#r173854928.

I've annotated the ones that could be useful/are necessary for correct functionality.

There is another bug that I fixed manually, some entries are missing rounding lines. For example,

```
2025-12-15 * "Fidelity" "BUY - [FXAIX] Fidelity 500 Index Fund"
  Assets:Fidelity:REDACTED 1.714 FXAIX {237.4562 USD}
  Assets:Fidelity:REDACTED -407 USD
```

It does not balance: `Transaction does not balance: (-0.0000732 USD)`

It's derived from
```csv
12/15/2025,"REDACTED","REDACTED","Contributions",,"FID 500 INDEX",,1.714,,,,,407,,
```

I would have expected `"rounding_error": "Expenses:RoundingErrors"` to be automatically added but that seems like it ought to be the job of a superclass...

Relevant config chunk:
```python
"transaction_type_map": {
    "CO CONTR": "dep",
    "DIVIDEND": "reinvest",
    "CONTRIBUTIONS": "buystock",
    "TRANSFER": "xfer",
    "PURCHASE INTO": "buystock",
},
"rounding_error": "Expenses:RoundingErrors",
"swap_quantity_and_price_values": True,
"security_description_map": {
    "FID 500 INDEX": "FXAIX",
    "VANG SM CAP IDX INST": "VSCIX",
    "VANG MIDCAP IDX ADM": "VIMAX",
    "VANG EM STK IDX ADM": "VEMAX",
    "VANG DEV MKT IDX IS": "VTMNX",
},
```

**Comment by scanta2** [comment]
> [@thehilll](https://github.com/thehilll) thanks! I've updated my version based on yours and here are the remaining changes: [thehilll@a9c43d9#r173854928](https://github.com/thehilll/beancount_reds_importers/commit/a9c43d911a16f8ca12fe2041e45b6f1ebf3ecb78#r173854928).
> 
> I've annotated the ones that could be useful/are necessary for correct functionality.
> 
> There is another bug that I fixed manually, some entries are missing rounding lines. For example,
> 
> ```
> 2025-12-15 * "Fidelity" "BUY - [FXAIX] Fidelity 500 Index Fund"
>   Assets:Fidelity:REDACTED 1.714 FXAIX {237.4562 USD}
>   Assets:Fidelity:REDACTED -407 USD
> ```
> 
> It does not balance: `Transaction does not balance: (-0.0000732 USD)`
> 
> It's derived from
> 
> ```
> 12/15/2025,"REDACTED","REDACTED","Contributions",,"FID 500 INDEX",,1.714,,,,,407,,
> ```
> 
> I would have expected `"rounding_error": "Expenses:RoundingErrors"` to be automatically added but that seems like it ought to be the job of a superclass...
> 
> Relevant config chunk:
> 
> "transaction_type_map": {
>     "CO CONTR": "dep",
>     "DIVIDEND": "reinvest",
>     "CONTRIBUTIONS": "buystock",
>     "TRANSFER": "xfer",
>     "PURCHASE INTO": "buystock",
> },
> "rounding_error": "Expenses:RoundingErrors",
> "swap_quantity_and_price_values": True,
> "security_description_map": {
>     "FID 500 INDEX": "FXAIX",
>     "VANG SM CAP IDX INST": "VSCIX",
>     "VANG MIDCAP IDX ADM": "VIMAX",
>     "VANG EM STK IDX ADM": "VEMAX",
>     "VANG DEV MKT IDX IS": "VTMNX",
> },

I have one more issue for contributions that are moved from "After Tax" to "Roth".
`12/15/2025,"RETIREMENT PLN","12345","Transfers",,"VANG EXT MKT IDX INS",,0.000,,,,,0.00,,`

These throw a `PriceCostBothZeroException` exception. I'd like to skip these transactions, instead. Some `Transfers` are legit transactions (i.e. my 401k is changing hands after a merger)

**Comment by scanta2** [comment]
> > I have one more issue for contributions that are moved from "After Tax" to "Roth". `12/15/2025,"RETIREMENT PLN","12345","Transfers",,"VANG EXT MKT IDX INS",,0.000,,,,,0.00,,`
> > These throw a `PriceCostBothZeroException` exception. I'd like to skip these transactions, instead.
> 
> I had a similar issue which I think my changes to `extract` which omit empty/zero-posting-only transactions end up resolving. So, perhaps that bit of my changes _is_ load bearing...

The code works, but if you set transfers to be a sellmf transaction (which I need for non-zero quantity transactions), then I still get the exception thrown.

**Comment by patbakdev** [comment]
> These throw a PriceCostBothZeroException exception. I'd like to skip these transactions, instead.

I haven't checked the latest updates to the code yet, but I believe we just need to add  `self.price_cost_both_zero_handler = lambda *args: None` to the `custom_init()` to avoid the error. See #178.

**Comment by sushain97** [comment]
> * Yes, the rounding error should’ve been added automatically. [@sushain97](https://github.com/sushain97) would you mind opening a separate bug for this and posting the test case?

Is there additional information required aside from what's in https://github.com/redstreet/beancount_reds_importers/issues/170#issuecomment-3707550005?

**Comment by scanta2** [comment]
> > [@thehilll](https://github.com/thehilll) the conversion using symbol_from_description happens too late. All the symbols at that point are `BANC`.
> 
> [@scanta2](https://github.com/scanta2) apologize that I've been away for a while...do you have a csv line that shows this? I see what you mean that it happens after some other manipulation to the symbol, but I want to make sure I know what is happening. Thanks.

All I had to do is to swap the `rdr.convert("Symbol"...)` lines order. I put `symbols_from_description` first, but I think it's fine as long as it's before `map_symbols`.  

Here's an example:
```
Run Date,Account,Account Number,Action,Symbol,Description,Type,Price ($),Quantity,Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
01/12/2026,"BLABLA 401(K) PLAN","12345","Exchange Out",,"MFS INTL DIVRSN R6",,-2812.729,,,,,-80725.32,,
```

The symbol column contains the description of the symbol, which is replaced using the appropriate dictionary.

**Comment by thehilll** [comment]
> I only have this in my importer config:
> 
> ```
> "security_description_map": {
>             "MFS INTL DIVRSN R6": "MDIZX",
>             "VANG INST 500 IDX TR": "US92202M757",
>             "VG IS EXT MKT IDX C": "US92202M716",
>             "VG IS TL INTL STK MK": "US92202M666",
>             "VG IS TOT BD MKT IDX": "US92202M625",
>         },
> ```
> 
> Some of those funds are private trusts, and don't have a "proper" symbol. In my commodity declarations, I use the CUSIP value as the symbol's name, for example:
> 
> ```
> 1994-05-25 commodity US92202M625
>   name: "Vanguard Institutional Total Bond Market Index Trust"
>   fullname: "VG IS TOT BD MKT IDX"
>   isin: "US92202M625"
>   a__isin: "US92202M625"
>   cusip: "US92202M625"
> ```
> 
> This is one of the `fund_info` entries: `074: ('US92202M625', 'US92202M625', 'Vanguard Institutional Total Bond Market Index Trust')`

I do think the conflict must be between `cusip_to_symbols` and `symbol_from_description`.  Here's my logic, let me know what you think:

- You have no value set for `security_symbol_map`, so `self.security_symbol_map` is `dict()` and the function `map_symbols` does:
```
self.security_symbol_map.get(s, s)
```
- In the case where the security has a description but no symbol this would be `{}.get("", "")` which just returns an empty string like we started with (so no change)
- `cusip_to_symbols` does a lookup in the `funds_by_id` dict which is keyed by CUSIP
```
self.funds_by_id = {i: (ticker, desc) for ticker, i, desc in self.fund_data}
```
- I can see two ways that this could come into play:
    - For these rows where the symbol is `''`, if you have _any_ row in `fund_info` that has an empty CUSIP it would match here
    - If the row has a CUSIP it would match and pick up your CUSIP used as symbol (though that seems not the case here b/c the example you gave has no symbol at all.

Is it possible there is any entry in `fund_info` with an empty CUSIP?  I just don't see how `map_symbols` is causing the issue here, and I'd like to figure out where all these various manipulations conflict before more people use this part.

**Comment by blalor** [comment]
I've recently added a number of Fidelity accounts and need to get my import workflow shored up. RIP OFX (and screw you, Fidelity).  Scanning this issue, it looks like there are a few different PRs related to outstanding Fidelity CSV parsing.  Can I help to get them landed?  Is there a particular branch/PR I should be using locally to validate?

**Comment by thehilll** [comment]
Red and I have been merging changes in here in small steps.  The most up-to-date PR for that is here:

https://github.com/redstreet/beancount_reds_importers/pull/176

Depending on the complexity of your accounts that might work.  The full version that I have been using since Fidelity did this is here:

https://github.com/thehilll/beancount_reds_importers/tree/fidelity_all_account_csv

See the `fidelity_all_account_csv` branch.  That has quite a few more options (though all should cause no harm if not configured, and I tried to comment in the importer what they do).  This has worked well for me for roughly five months and over a prior year of transactions.  Fidelity does provide very slightly different data in the csv which just cannot be addressed, but it isn't too bad.

**Comment by blalor** [comment]
Thank you @thehilll.  I'm trying out your branch for the time being.  I'm having trouble with dividend transactions; I'm not sure it's directly related to this issue but it is under the umbrella of OFX alternatives; I'll move this to a separate discussion or issue if that's better.

I've got some old ofx downloads and I'm trying to get equivalent transactions extracted out of the CSV (both single- and multiple-account exports).  The account in question has `FZFXX` (`316341304`, "FIDELITY TREASURY MONEY MARKET FUND") as the core position.  The OFX-extracted transaction that I have in my ledger and makes sense to me looks like:

```
2024-11-29 * "DIVIDEND RECEIVED" "[FZFXX]"
  filing_account: "Assets:Fidelity"
  Assets:Fidelity:Cash                 11.2800 USD
  Income:Investments:Dividends:FZFXX  -11.2800 USD
```

This looks correct: I've received a dividend as income and it's increasing the inventory of my cash account.


<details><summary>importer config</summary>

```python
from beancount_reds_importers.importers import fidelity as FidelityOFX
from beancount_reds_importers.importers.fidelity import fidelity_all_accounts_csv

import beangulp

old_account_config = {
    "account_number": "…",
    "balance_assertion_date_type": "ofx_date",

    "main_account": "Assets:Fidelity:{ticker}",
    "cash_account": "Assets:Fidelity:Cash",
    "dividends": "Income:Investments:Dividends:{ticker}",
    "capgainsd_lt": "Income:Investments:CapGains:Long:{ticker}",
    "capgainsd_st": "Income:Investments:CapGains:Short:{ticker}",
    "cg": "Income:Fidelity:PnL",
    "interest": "Income:Investments:Interest",
    "fees": "Expenses:Finance:Fees",
    "rounding_error": "Equity:Rounding-Errors",
    "fund_info": {
        "fund_data": [
            # there's more…
            ("FZFXX", "316341304", "FIDELITY TREASURY MONEY MARKET FUND"),
        ],
        "money_market": [
            # "FZFXX",
        ]
    },
    ## for csv
    "currency": "USD",
}

beangulp.Ingest([
    FidelityOFX.Importer(old_account_config),
    fidelity_all_accounts_csv.Importer(old_account_config),
]).ingest()
```

</details>

Listing `FZFXX` in `fund_info.money_market` doesn't impact the OFX-extracted transaction.

<details><summary>ofx transaction detail</summary>

The OFX export shows this, from `ofx-summarize`:
```
2024-11-29 05:00:00 income DIVIDEND RECEIVED 11.2800
```
Dropping into the debugger and dumping that transaction shows
```python
{'commission': Decimal('0'),
 'fees': Decimal('0'),
 'id': '…',
 'income_type': 'DIV',
 'memo': 'DIVIDEND RECEIVED',
 'security': '316341304',
 'settleDate': None,
 'tferaction': None,
 'total': Decimal('11.2800'),
 'tradeDate': datetime.datetime(2024, 11, 29, 5, 0),
 'type': 'income',
 'unit_price': Decimal('0'),
 'units': Decimal('0')}
```

I don't know how to export more OFX context without revealing more transaction info than I'm comfortable with.
</details>

<details><summary>multiple-account csv transaction detail</summary>

```csv
Run Date,Account,Account Number,Action,Symbol,Description,Type,Exchange Quantity,Exchange Currency,Currency,Price,Quantity,Exchange Rate,Commission,Fees,Accrued Interest,Amount,Settlement Date
11/29/2024,"Individual - TOD","MYACCTNUM","REINVESTMENT FIDELITY TREASURY MONEY MARKET FUND (FZFXX) (Cash)",FZFXX,"FIDELITY TREASURY MONEY MARKET FUND",Cash,0,,USD,1,11.28,0,,,,-11.28,
11/29/2024,"Individual - TOD","MYACCTNUM","DIVIDEND RECEIVED FIDELITY TREASURY MONEY MARKET FUND (FZFXX) (Cash)",FZFXX,"FIDELITY TREASURY MONEY MARKET FUND",Cash,0,,USD,,0.000,0,,,,11.28,
```

</details>

The transactions exported using @thehilll's `fidelity_all_accounts_csv.Importer` are

```
2024-11-29 * "REINVESTMENT FIDELITY TREASURY MONEY MARKET FUND (FZFXX) (Cash)" "[FZFXX] FIDELITY TREASURY MONEY MARKET FUND"
  filing_account: "Assets:Fidelity"
  Assets:Fidelity:FZFXX   11.28 FZFXX {1 USD}
  ; or, with FZFXX in fund_info.money_market:
  ; Assets:Fidelity:FZFXX   11.28 FZFXX @ 1 USD
  Assets:Fidelity:Cash   -11.28 USD

2024-11-29 * "DIVIDEND RECEIVED FIDELITY TREASURY MONEY MARKET FUND (FZFXX) (Cash)" "[FZFXX] FIDELITY TREASURY MONEY MARKET FUND"
  filing_account: "Assets:Fidelity"
  Assets:Fidelity:Cash                 11.28 USD
  Income:Investments:Dividends:FZFXX  -11.28 USD
```

The reinvestment transaction throws off my cash balance.  Is there a way to get the CSV importers (single- and multiple-account importers give the same result) so that the reinvestment is effectively dropped when the reinvestment is buying the same security as the core position? (I'm not 100% positive I'm asking this correctly, I just know that reinvestment transaction is throwing off my balance).

**Comment by thehilll** [comment]
@blalor sorry to be so slow to reply.

I run into this issue as well.  I would like the same outcome that you are seeking, namely that the income is from the security income account and is deposited in the cash account.

I think the start of this issue is that there is different information in the `ofx` file and the `csv` one.  In the `ofx` file I only see the income line item.  In the `csv` file I see that transaction _and_ a reinvestment one.

Given that, it isn't surprising that the beancount transactions are different.  What I'm not clear about is whether different settings could address this.  I have tried playing around with `fund_info.money_market` and the config item `cash_account`, but I haven't had any luck.

I'm not sure it is fixable as fidelity does not show any transactions for e.g. `Assets:Fidelity:FZFXX` other than these reinvestments.  So I don't think you could use that for `cash_account`.  I guess we could add some config for accounts to ignore reinvestments for?  That seems rather complex though.

I'm very open to suggestions here.  I've been manually deleting these transactions since I switched to the `csv` import.

**Comment by patbakdev** [comment]
I too am running into this issue and have just been manually deleting them. And I am "ok" continuing to do so, but it would be nice to not have to. The matter seems to be pretty clear for me. Its always a specific FUND. So having the option to exclude that ticker would work for me. 

As to the larger issue. I have been running with the same frankenstein setup ( main branch + the other branch with extra changes) since this issue was first brought up. Downside, I have no idea what state things are in.. Upside, I haven't ran into a single problem (other than this one mentioned above) and am quite pleased to not have to have thought about this over the last 6 months. :)

**Comment by thehilll** [comment]
> I too am running into this issue and have just been manually deleting them. And I am "ok" continuing to do so, but it would be nice to not have to. The matter seems to be pretty clear for me. It's always a specific FUND. So having the option to exclude that ticker would work for me.

Good point.  I just added a config option in my branch to allow a list of securities for which you would like to ignore purchase transactions.  Reviewing my `csv` files the only purchases of these that I have are for reinvestments that I would like to ignore, but maybe that's not always true.

> 
> As to the larger issue. I have been running with the same frankenstein setup ( main branch + the other branch with extra changes) since this issue was first brought up. Downside, I have no idea what state things are in.. Upside, I haven't ran into a single problem (other than this one mentioned above) and am quite pleased to not have to have thought about this over the last 6 months. :)

Red and I had been working to merge the branch that I have done with all of the changes into this repo step by step, but we haven't progressed far on that.  I should have more time coming up and will ping him on the open PR for this process when I do.

**Comment by thehilll** [comment]
For anyone using this, Fidelity seems to have changed their `csv` format within the last week.  I have noticed two changes:

1. They changed the date format from `%m/%d/%Y` to `%m-%d-%Y`.  This used to require a change to the importer, but in addition to changing the default I just added a config item `fidelity_dt_fmt` which would allow you to set a new value in the case that they change this again
2. My downloads today did not include the CUSIP code as the symbol for individually held municipal bonds.  This is frustrating, but it was already possible to match the bond using its description via the config item `security_description_map`.  This can be constructed automatically from `fund_info` assuming your descriptions in there match what Fidelity uses in the `csv` (they did for me which means they have been consistent since I bought the bonds).  I suspect few people will run into this, but it's there.  Should they revert back to providing the CUSIP that would take precedence w/o any config change.

This is all fairly frustrating...it's possible to parse this `csv` fairly successfully, but Fidelity clearly just doesn't care enough about our use case to keep the format consistent.

**Comment by thehilll** [comment]
One other change Fidelity has made...they are no longer quoting the `csv` fields.  They do provide quotes for empty fields, but not for fields other than that (e.g. `Action` or `Description`).

Because of this fields with a comma in them (in my case bill payment recipients I have used for years whose names have always had commas) break the parsing entirely.  This week I just manually edited those, but I'm not sure there's an easy way to handle this within the importer.  It would have to happen before the file is read, and the fix isn't easy (in my case I could probably do a find/replace, but that's obviously not a general solution).

**Comment by patbakdev** [comment]
Thanks for the heads up. I downloaded from Fidelity and Monday and didn't run into any noticeable problems, but I didn't have a lot of data. I'll keep an eye out for next time. 

Ok. The comma thing is just stupid. So stupid I just had to login and take a look. Some empty columns are quoted, some are not. LibreCalc won't even load this trash properly. Uhg.

Maybe there is a a setting in petl or a different back end (csv.DictReader [*](https://www.py4u.org/blog/python-parse-csv-ignoring-comma-with-double-quotes)) that would work better. The columns - I "assume" will not ever have a comma in their names. Using that knowledge as a base along with some knowledge about those columns - only Account, Action, and Description would ever have commas in their data - might allows us to come up with some approach and pre-fix the file somewhere like in 'read_raw'.  

Or maybe there is another common pattern - all "real" commas have a space afterward.

Sometimes I think all importers would benefit from a text pre-processor map that does replace "A" pattern with "B" - maybe even with regex. Basically automate what we all end up having to do manually when this stuff happens.

Just throwing out half-baked ideas at this point.

**Comment by patbakdev** [comment]
I just downloaded my Account and Positions. Looks like they reverted the date format change back to slashes in the accounts. But they also changed the headers for the Positions. I didn't have a change to look at the code, so I just pasted an old header from a previous csv over the new one. (Columns seem to be the same).

Old Column Names:
```
Account Number,Account Name,Symbol,Description,Quantity,Last Price,Last Price Change,Current Value,Today's Gain/Loss Dollar,Today's Gain/Loss Percent,Total Gain/Loss Dollar,Total Gain/Loss Percent,Percent Of Account,Cost Basis Total,Average Cost Basis,Type
```

New Column Names:
```
﻿Account number,Account name,Symbol,Description,Quantity,Last price,Last price change,Current value,Today's gain/loss dollar,Today's gain/loss percent,Total gain/loss dollar,Total gain/loss percent,Percent of account,Cost basis total,Average cost basis,Type
```

Looks to be all casing. Should be an easy fix. But may want to wait to see if they change it back.

**Comment by thehilll** [comment]
I literally had a todo item to come make this exact point.  They also reverted the bug on quoting text fields which is good.

I handled this manually, but I agree...might as well wait a bit to see if they revert this as well.  I was thinking about the fix, and I think something that might survive simple changes like this might be easiest.  Not sure if that can be handled in the context of the importer or if it would need some sort of preflight script.

One other thing I noticed is that there were some slight changes in the descriptions of a couple of my municipal bonds.  Without the CUSIP in the file those descriptions are important for identifying the security.  It _appears_ that these are only recently purchased bonds (and new issues at that), so hopefully they will stay stable after this.  This issue should not trouble many people...only if you purchase individual bonds.

**Comment by patbakdev** [comment]
EDIT: Never-mind...this allowed the import to succeed, but seemed to have broke something (all non-USD numbers are 0).

I didn't have any new transactions for this week. So I just pulled the positions. The column headers for this file are still busted/changed. The quick manual fix is to just copy over the header line from an older file or manually title case each entry. But I decided to fix the importer for now, for myself. Easy enough to revert back. I don't think this file `fidelity_all_account_positions_csv.py` is in the active tree. I may have just snagged it from the WIP branch we had going at some point. So for now, in case anyone wants it, here is the patch/diff that I made. (Keep in mind your base copy may be different).

```
diff --git a/beancount_reds_importers/importers/fidelity/fidelity_all_account_positions_csv.py b/beancount_reds_importers/importers/fidelity/fidelity_all_account_positions_csv.py
index 2ace641..959ed7c 100644
--- a/beancount_reds_importers/importers/fidelity/fidelity_all_account_positions_csv.py
+++ b/beancount_reds_importers/importers/fidelity/fidelity_all_account_positions_csv.py
@@ -19,22 +19,22 @@ class Importer(investments.Importer, csvreader.Importer):
         self.file_encoding = "utf-8-sig"
         self.filename_pattern_def = "Portfolio_Positions_.*.csv"
         self.header_identifier = (
-            "^Account Number,Account Name,Symbol,Description,Quantity.*"
+            "^Account number,Account name,Symbol,Description,Quantity.*"
         )
         self.get_ticker_info = self.get_ticker_info_from_id
         self.date_format = "%b-%d-%Y"
         self.funds_db_txt = "funds_by_ticker"
         self.fix_muni_shares = True  # see prepare_raw_file, fidelity reports 100x share values for muni bonds
-        self.column_labels_line = "Account Number,Account Name,Symbol,Description,Quantity,Last Price,Last Price Change,Current Value,Today's Gain/Loss Dollar,Today's Gain/Loss Percent,Total Gain/Loss Dollar,Total Gain/Loss Percent,Percent Of Account,Cost Basis Total,Average Cost Basis,Type"
+        self.column_labels_line = "Account number,Account name,Symbol,Description,Quantity,Last price,Last price change,Current value,Today's gain/loss dollar,Today's gain/loss percent,Total gain/loss dollar,Total gain/loss percent,Percent of account,Cost basis total,Average cost basis,Type"
         # fmt: off
         self.header_map = {
             "Description": "memo",
             "Symbol": "security",
             "date": "date",
             "Quantity": "units",
-            "Last Price": "unit_price",
-            "Account Number": "account_number",
-            "Current Value": "balance",
+            "Last price": "unit_price",
+            "Account number": "account_number",
+            "Current value": "balance",
         }
         # fmt: on
         self.skip_transaction_types = []
@@ -118,7 +118,7 @@ class Importer(investments.Importer, csvreader.Importer):
             try to identify this and adjust by dividing by 100
             """
             # if quantity is None or row["Price"] is None or row["Amount"] is None:
-            if None in [quantity, row["Last Price"], row["Current Value"]] or "" in [
+            if None in [quantity, row["Last price"], row["Current value"]] or "" in [
                 quantity,
                 row["Last Price"],
                 row["Current Value"],
@@ -134,8 +134,8 @@ class Importer(investments.Importer, csvreader.Importer):
                     rel_tol=1e-09,
                     abs_tol=1e-09,
                 ):
-                    numeric_value = re.sub(r"[^0-9\.]", "", row["Current Value"])
-                    numeric_price = re.sub(r"[^0-9\.]", "", row["Last Price"])
+                    numeric_value = re.sub(r"[^0-9\.]", "", row["Current value"])
+                    numeric_price = re.sub(r"[^0-9\.]", "", row["Last price"])
                     inferred_price = round(
                         abs(float(numeric_value)) / abs(float(quantity)), 4
                     )
@@ -164,7 +164,7 @@ class Importer(investments.Importer, csvreader.Importer):
         if getattr(self, "fix_muni_shares", False):
             rdr = rdr.convert("Quantity", adjust_muni_share_count, pass_row=True)
 
-        for f in ["Last Price", "Quantity"]:
+        for f in ["Last price", "Quantity"]:
             rdr = rdr.convert(f, add_precision)
 
         return rdr
```

**Comment by thehilll** [comment]
> EDIT: Never-mind...this allowed the import to succeed, but seemed to have broke something (all non-USD numbers are 0).

I had tried to do something similar and ran into an issue as well (can't recall if it was the same).  I'm sure it is possible to make this work, but I wonder if it is the most robust fix.

I was thinking it might be better to do something like
```
read csv
do case insensitive match on the current header line
if found replace that line with the one currently assumed by the importer (will differ by at most the casing)
if not found do nothing
```

I don't know if this can be done as part of the importer framework, but it does not seem to be the worst ting to have an external script do this.  I have to believe anyone using this has some sort of process built up where they could use that.

> 
> I didn't have any new transactions for this week. So I just pulled the positions. The column headers for this file are still busted/changed. The quick manual fix is to just copy over the header line from an older file or manually title case each entry. But I decided to fix the importer for now, for myself. Easy enough to revert back. I don't think this file `fidelity_all_account_positions_csv.py` is in the active tree. I may have just snagged it from the WIP branch we had going at some point. So for now, in case anyone wants it, here is the patch/diff that I made. (Keep in mind your base copy may be different).

My WIP fork is here:

https://github.com/thehilll/beancount_reds_importers/blob/fidelity_all_account_csv/beancount_reds_importers/importers/fidelity/fidelity_all_account_positions_csv.py

**Comment by patbakdev** [comment]
I definitely think the headers should be case insensitive. I was hoping I could quickly hack together a fix, but when it didn't work out of the gate I just manually did it. I got "stuff' going on and don't have the time to investigate further. It seems like a simple rename should have worked, but I just wasn't able to dig into why not.

**Comment by patbakdev** [comment]
Ok. That patch was more or less good, I just missed a rename. I will submit a pull request against @thehilll 's branch for now. Its probably not the proper long-term fix, but I'm getting tired of manually fixing the headers. Do with it as you will.

PR: https://github.com/thehilll/beancount_reds_importers/pull/1
